### ISSUE TITLE
Toolbar

### ISSUE THREAD

**Issue by ahmedlhanafy** [callstack-io/react-native-paper#20]
[MD Docs Link](https://material.google.com/components/toolbars.html#)

**Comment by ferrannp** [comment]
@satya164 & @ahmedlhanafy do we want to reuse here for Android [ToolbarAndroid](https://facebook.github.io/react-native/docs/toolbarandroid.html) and then build the iOS one? Or we want both in pure JS? I am talking about reusing because it implements cool features already like RTL.

**Comment by satya164** [comment]
Reusing native one doesn't provide much value here IMO. We will have to re-implement those features like RTL in JS for iOS anyways. Also `ToolbarAndroid` is pretty limited in customisation, so there is that.
